# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - resumefilterapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://resumefilterapp.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_aacccf95a053462a8e7b8aa3c79c04f8 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_3bdff5f2fe074a4683a66e6ca32a56b1 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: resumefilterapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_aacccf95a053462a8e7b8aa3c79c04f8 }}/resumefilterapp:${{ github.sha }}
          file: ./Dockerfile

    deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'Production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'resumefilterapp'
            slot-name: 'Production'
            publish-profile: ${{ secrets.AzureAppService_PublishProfile_dcbdaf83ad144241b0f1f3b56862b988 }}
            images: 'resumefilterapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_aacccf95a053462a8e7b8aa3c79c04f8 }}/resumefilterapp:${{ github.sha }}'
